# Generated by Django 5.1.3 on 2024-11-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AulaAvaliada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=15)),
                ('aula', models.CharField(max_length=100)),
                ('avaliacao', models.CharField(choices=[('😃', 'Ótimo'), ('😐', 'Regular'), ('☹️', 'Ruim')], max_length=10)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetorAvaliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('setor', models.CharField(max_length=100)),
                ('avaliacao', models.CharField(choices=[('otimo', 'Ótimo'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=10)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
