# Generated by Django 5.1.3 on 2024-11-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setoravaliado',
            name='setor',
            field=models.CharField(choices=[('recepcao', 'Recepção'), ('financeiro', 'Financeiro'), ('academico', 'Acadêmico'), ('biblioteca', 'Biblioteca'), ('nti', 'NTI')], max_length=20),
        ),
    ]
