# Generated by Django 5.1.3 on 2024-11-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_setoravaliado_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulaavaliada',
            name='curso',
            field=models.CharField(choices=[('administracao', 'Administração'), ('ciencias_contabeis', 'Ciências Contábeis'), ('direito', 'Direito'), ('educacao_fisica', 'Educação Física'), ('enfermagem', 'Enfermagem'), ('fisioterapia', 'Fisioterapia'), ('fonoaudiologia', 'Fonoaudiologia'), ('pedagogia', 'Pedagogia'), ('psicologia', 'Psicologia'), ('servico_social', 'Serviço Social'), ('sistemas_informacao', 'Sistemas de Informação')], default='administracao', max_length=30),
        ),
        migrations.AlterField(
            model_name='aulaavaliada',
            name='avaliacao',
            field=models.CharField(choices=[('otimo', 'Ótimo'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=10),
        ),
    ]
